CREATE SCHEMA COMPANHIA;
USE COMPANHIA;

CREATE TABLE COMPANHIA.EMPREGADO(
	PNOME VARCHAR(15) NOT NULL,
	MNOME CHAR,
	SNOME VARCHAR(15) NOT NULL,
	NSS CHAR(9) NOT NULL,
	DATANASC DATE,
	ENDERECO VARCHAR(30),
	SEXO CHAR,
	SALARIO DECIMAL(10, 2),
	NSSSUPER CHAR(9),
	NDEP INT NOT NULL

);

CREATE TABLE COMPANHIA.DEPARTAMENTO(
	DNOME VARCHAR(15) NOT NULL,
	DNUMERO INT NOT NULL,
	NSSGER CHAR(9) NOT NULL,
	DATINICGER DATE
    
);

CREATE TABLE COMPANHIA.LOCAIS_DEPTO(
	DNUMERO INT NOT NULL,
	DLOCALIZACAO VARCHAR(15) NOT NULL

);

CREATE TABLE COMPANHIA.PROJETO(
	PNOME VARCHAR(15) NOT NULL,
	PNUMERO INT NOT NULL,
	PLOCALIZACAO VARCHAR(15),
	DNUM INT NOT NULL

);

CREATE TABLE TRABALHA_EM(
	NSSEMP CHAR(9) NOT NULL,
	PNRO INT NOT NULL,
	HORAS DECIMAL(3,1) NOT NULL
    
);

CREATE TABLE DEPENDENTE(
	NSSEMP CHAR(9) NOT NULL,
	NOMEDEPENDENTE VARCHAR(15) NOT NULL,
	SEXO CHAR,
	DATANIV DATE,
	RELACAO VARCHAR(8)
    
);

ALTER TABLE EMPREGADO ADD PRIMARY KEY (NSS);
ALTER TABLE DEPARTAMENTO ADD PRIMARY KEY (DNUMERO);
ALTER TABLE LOCAIS_DEPTO ADD PRIMARY KEY (DNUMERO, DLOCALIZACAO);
ALTER TABLE PROJETO ADD PRIMARY KEY (PNUMERO);
ALTER TABLE TRABALHA_EM ADD PRIMARY KEY (NSSEMP, PNRO);
ALTER TABLE DEPENDENTE ADD PRIMARY KEY (NSSEMP, NOMEDEPENDENTE);

ALTER TABLE EMPREGADO ADD FOREIGN KEY (NDEP) REFERENCES DEPARTAMENTO (DNUMERO);
ALTER TABLE EMPREGADO ADD FOREIGN KEY (NSSSUPER) REFERENCES EMPREGADO (NSS) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE DEPARTAMENTO ADD FOREIGN KEY (GERSSN) REFERENCES EMPREGADO (NSS) ON DELETE CASCADE;

ALTER TABLE LOCAIS_DEPTO ADD FOREIGN KEY (DNUMERO) REFERENCES DEPARTAMENTO (DNUMERO) ON DELETE CASCADE;
                         
ALTER TABLE PROJETO ADD FOREIGN KEY (DNUM) REFERENCES DEPARTAMENTO (DNUMERO);				

ALTER TABLE TRABALHA_EM ADD FOREIGN KEY (PNRO) REFERENCES PROJETO (PNUMERO) ON DELETE CASCADE;
ALTER TABLE TRABALHA_EM ADD FOREIGN KEY (NSSEMP) REFERENCES EMPREGADO (NSS) ON DELETE CASCADE;

ALTER TABLE DEPENDENTE ADD FOREIGN KEY (NSSEMP) REFERENCES EMPREGADO (NSS);
